import pygame


# Global constants

# Tile textures by type
TEXTURES: dict[str, pygame.Surface] = {
    "ground": pygame.image.load("../resources/Textures/Floor.png"),  # ground
    "wall": pygame.image.load("../resources/Textures/Wall.png"),  # walls
    "lava": pygame.image.load("../resources/Textures/Lava.png"),  # lava
    "ice": pygame.image.load("../resources/Textures/Ice.png"),  # ice
    "sand": pygame.image.load("../resources/Textures/Sand.png"),  # sand
    "bush": pygame.image.load("../resources/Textures/Bush.png"),  # bush
}

# Icon textures for UI
ICONS: dict[str, pygame.Surface] = {
    "heart": pygame.image.load("../resources/Icons/Heart.png"),  # HP icon
    "power": pygame.image.load("../resources/Icons/Power.png"),  # Power icon
    "explosion": pygame.image.load(
        "../resources/Icons/Explosion.png"
    ),  # Explosion icon
    "shield": pygame.image.load("../resources/Icons/Shield.png"),  # Shield icon
}


TILE_SIZE: int = 0  # will be assigned during runtime in main.py
COLUMNS: int = 48  # number of tile columns (horizontal)
ROWS: int = 27  # number of tile rows (vertical)
ROBOT_RENDER_SIZE = 64  # always 64x64 px
SHOW_STATS: bool = True  # Toggle to show or hide HP and Power numbers


# Texts
texts = {
    "start_text": "Start Game",
    "difficulty_text": "Difficulty",
    "instructions_text": "How to play",
    "level_text": "Map Selection",
    "settings_text": "Settings",
    "quit_text": "Exit Game",
    "main_menu_text": "Main Menu",
    "easy_text": "Easy",
    "medium_text": "Medium",
    "hard_text": "Hard",
    "normal_mode_text": "Normal",
    "back_text": "Back",
    "continue_text": "Continue",
    "paused_text": "Paused",
    "spider_text": "Spider",
    "tank_text": "Tank",
    "class_selection_text": "Robot Selection",
    "map1_text": "Map 1",
    "map2_text": "Map 2",
    "level_selection_text": "Map Selection",
    "english_text": "English",
    "german_text": "German",
    "show_credits_text": "Show Credits",
    "volume_text": "Volume",
    "language_text": "Language",
    "credits_text": "Credits",
    "victory_text": "VICTORY",
    "endgame_text": ["Press ECS to return to main menu", "or ENTER to play again"],
    "gameover_text": "GAME OVER",
    "go_text": "GO!",
    "credits": [
        "This game is a work of Team 2:",
        "Walid Abdulhamid, Katja Grammel, Sarah Herty and Nico Loroff",
        "We only used openly available pictures and sounds with licence cc0.",
    ],
    "instructions": [
        "Robots:",
        "   Generally:",
        "      Health:",
        "          • everyone starts with 100",
        "          • lost through damages (shots, lava)",
        "          • when 0 is reached, robor dies",
        "      Engergy:",
        "          • everyone starts with 100",
        "          • loss through firing shots, but recharge over time",
        "   Tank:",
        "      Controls:",
        "          • w/s keys for moving forward/backward",
        "          • a/d keys for turning left/right",
        "          • mouse can aim +/- 45° and click for shooting",
        "      Else:",
        "          • bullets reach farther",
        "          • decreases damage by 1/3",
        "          • attack needs 20 energy",
        "      Overall: harder to steer, does more damage and gets less damage",
        "   Spider:",
        "      Controls:",
        "          • w/a/s/d keys for moving",
        "          • mouse for turning/aiming and click for shooting",
        "      Else:",
        "          • decreases attack by 1/3",
        "          • attack needs 15 energy",
        "      Overall: easy to steer, does less damage and gets more damage",
        "",
        "Powerups:",
        "       Ram:",
        "           2x speed and collision attack (lasts 5 seconds)",
        "       Health-boost:",
        "           + 50 health (instantly)",
        "       Power-boost:",
        "           + 50 power (instantly)",
        "       Shield:",
        "           • indestructible against bullets (lasts 5 seconds)",
        "           • still damage from lava",
        "",
        "Modes:",
        "   Easy:",
        "       • 3 robots (1 player and 2 npcs)",
        "       • player has a speed advantage",
        "       • goal: be the last one alive",
        "   Medium:",
        "       • 4 robots (1 player and 3 npcs)",
        "       • player has a slight speed advantage",
        "       • goal: be the last one alive",
        "   Hard:",
        "       • 5 robots (1 player and 4 npcs)",
        "       • there are no speed advantages",
        "       • goal: be the last one alive",
        "   Survival1:",
        "       • in an increasingly fast time a new enemy appears",
        "       • hiding in bush does not work in survival mode",
        "       • one-shot-kill for enemies",
        "       • goal: survive as long as you can, make a new highscore",
        "   Survival2:",
        "       • always has 3 robots, everytime one dies, a faster one apppears",
        "       • hiding in bush does not work in survival mode",
        "       • one-shot-kill for enemies",
        "       • goal: survive as long as you can, make a new highscore",
        "",
        "Surfaces:",
        "   Grass:",
        "       no effect",
        "   Wall:",
        "       can not pass",
        "   Sand:",
        "       slower speed (while on sand)",
        "   Ice:",
        "       higher speed (while on ice)",
        "   Bush:",
        "       • invisible for all (while completly in bush)",
        "       • hiding in bush does not work in survival mode",
        "   Lava:",
        "       40 damage and respawn on safe surface",
    ],
    "lava_river": "Lava River",
    "four_elements": "Four Elements",
    "Random": "Random",
    "survival_mode_text": "Survival",
}


def update_language(language):
    global texts
    if language == "German":
        texts = {
            "start_text": "Spiel starten",
            "difficulty_text": "Schwierigkeit",
            "instructions_text": "Anleitung",
            "level_text": "Karten-Auswahl",
            "settings_text": "Einstellungen",
            "quit_text": "Spiel beenden",
            "main_menu_text": "Hauptmenü",
            "easy_text": "Leicht",
            "medium_text": "Mittel",
            "hard_text": "Schwer",
            "normal_mode_text": "Normal",
            "back_text": "Zurück",
            "continue_text": "Fortsetzen",
            "paused_text": "Pausiert",
            "spider_text": "Spinne",
            "tank_text": "Panzer",
            "class_selection_text": "Roboter Auswahl",
            "map1_text": "Karte 1",
            "map2_text": "Karte 2",
            "level_selection_text": "Karten Auswahl",
            "english_text": "Englisch",
            "german_text": "Deutsch",
            "show_credits_text": "Zeig die Credits",
            "volume_text": "Lautstärke",
            "language_text": "Sprache",
            "credits_text": "Credits",
            "victory_text": "Sieg",
            "endgame_text": [
                "Drücke ESC um ins Hauptmenü zurückgehen",
                "oder ENTER um nochmal zu spielen",
            ],
            "gameover_text": "Verloren",
            "go_text": "LOS!",
            "credits": [
                "Dieses Spiel ist ein Projekt der Gruppe 2:",
                "Walid Abdulhamid, Katja Grammel, Sarah Herty und Nico Loroff",
                "Wir haben nur frei verfügbare Bilder und Töne mit Lizenz cc0 verwendet.",
            ],
            "instructions": [
                "Roboter:",
                "   Allgemein:",
                "      Gesundheit:",
                "          • Jeder startet mit 100",
                "          • geht durch Schaden (Lava, Geschosse) verloren",
                "          • der Roboter stirbt wenn man 0 erreicht",
                "      Engergie:",
                "          • Jeder startet mit 100",
                "          • wird beim Schießen um benötigte Energie verringert",
                "   Panzer:",
                "      Steuerung:",
                "          • w/s Tasten fürs vorwärts/rückwärts Bewegen",
                "          • a/d Tasten fürs links/rechts Drehen",
                "          • Maus zum +/- 45° Zielen und Klicken zum Schießen",
                "      Sonstiges:",
                "          • Kugeln haben längere Flugbahn",
                "          • vermindert Schaden um 1/3",
                "          • Schießen braucht 20 Energie",
                "      Insgesamt: schwer zu steuern, macht mehr "
                + "und bekommt weniger Schaden",
                "   Spinne:",
                "      Steuerung:",
                "          • w/a/s/d Tasten fürs Bewegen",
                "          • Maus zum Drehen/Zielen und Klicken zum Schießen",
                "      Sonstiges:",
                "          • verringert Angriff um 1/3",
                "          • Schießen braucht 15 Energie",
                "      Insgesamt: leicht zu steuern, macht weniger "
                + "und bekommt mehr Schaden",
                "",
                "Powerups:",
                "       Rammbock:",
                "           2x Schnelligkeit und Kollisionsattacke (hält für 5 Sek.)",
                "       Gesundheitsbooster:",
                "           + 50 Gesundheit (sofort)",
                "       Energiebooster:",
                "           + 50 Energie (sofort)",
                "       Schild:",
                "           • geschützt gegen Schüsse (hält für 5 Sekunden)",
                "           • immer noch Schaden von Lava",
                "",
                "Modi:",
                "   Leicht:",
                "       • 3 Roboter (1 Spieler und 2 npcs)",
                "       • Spieler hat ein Geschwindigkeits-Vorteil",
                "       • Ziel: Sei der Letzte, der lebt",
                "   Mittel:",
                "       • 4 Roboter (1 Spieler und 3 npcs)",
                "       • Spieler hat ein kleinen Geschwindigkeits-Vorteil",
                "       • Ziel: Sei der Letzte, der lebt",
                "   Schwer:",
                "       • 5 Roboter (1 Spieler und 4 npcs)",
                "       • Hier gibt es keinen Geschwindigkeits-Vorteil",
                "       • Ziel: Sei der Letzte, der lebt",
                "   Survival1:",
                "       • Es erscheinen immer schneller neue Feinde",
                "       • Im Gebüsch verstecken funktioniert in survival mode nicht",
                "       • Gegner werden mit einem Schuss getötet",
                "       • Ziel: Überlebe so lange du kannst, erreiche einen Highscore",
                "   Survival2:",
                "       • Wenn einer, der 3 Roboter stirbt, kommt ein schnellerer",
                "       • Im Gebüsch verstecken funktioniert in survival mode nicht",
                "       • Gegner werden mit einem Schuss getötet",
                "       • Ziel: Überlebe so lange du kannst, erreiche einen Highscore",
                "",
                "Oberflächen:",
                "   Gras:",
                "       kein EffeKt",
                "   Wand:",
                "       Absperrrung, kann nicht durchfahren werden.",
                "   Sand:",
                "       verlangsamt (während man auf Sand ist)",
                "   Eis:",
                "       verschnellert (während man auf Eis ist)",
                "   Busch:",
                "       • unsichtbar für alle (während man komplett in Busch ist)",
                "       • verstecken im Gebüsch funktioniert in survival mode nicht",
                "   Lava:",
                "       40 Schaden und respawn auf sicherer Oberfläche",
            ],
            "lava_river": "Lava Fluss",
            "four_elements": "Vier Elemente",
            "Random": "Zufall",
            "survival_mode_text": "Survival",
        }
    else:
        texts = {
            "start_text": "Start Game",
            "difficulty_text": "Difficulty",
            "instructions_text": "How to play",
            "level_text": "Map Selection",
            "settings_text": "Settings",
            "quit_text": "Exit Game",
            "main_menu_text": "Main Menu",
            "easy_text": "Easy",
            "medium_text": "Medium",
            "hard_text": "Hard",
            "normal_mode_text": "Normal",
            "back_text": "Back",
            "continue_text": "Continue",
            "paused_text": "Paused",
            "spider_text": "Spider",
            "tank_text": "Tank",
            "class_selection_text": "Robot Selection",
            "map1_text": "Map 1",
            "map2_text": "Map 2",
            "level_selection_text": "Map Selection",
            "english_text": "English",
            "german_text": "German",
            "show_credits_text": "Show Credits",
            "volume_text": "Volume",
            "language_text": "Language",
            "credits_text": "Credits",
            "victory_text": "VICTORY",
            "endgame_text": [
                "Press ECS to return to main menu",
                "or ENTER to play again",
            ],
            "gameover_text": "GAME OVER",
            "go_text": "GO!",
            "credits": [
                "This game is a work of Team 2:",
                "Walid Abdulhamid, Katja Grammel, Sarah Herty and Nico Loroff",
                "We only used openly available pictures and sounds with licence cc0.",
            ],
            "instructions": [
                "Robots:",
                "   Generally:",
                "      Health:",
                "          • everyone starts with 100",
                "          • lost through damages (shots, lava)",
                "          • when 0 is reached, robor dies",
                "      Engergy:",
                "          • everyone starts with 100",
                "          • loss through firing shots, but recharge over time",
                "   Tank:",
                "      Controls:",
                "          • w/s keys for moving forward/backward",
                "          • a/d keys for turning left/right",
                "          • mouse can aim +/- 45° and click for shooting",
                "      Else:",
                "          • bullets reach farther",
                "          • decreases damage by 1/3",
                "          • attack needs 20 energy",
                "      Overall: harder to steer, does more damage and gets less damage",
                "   Spider:",
                "      Controls:",
                "          • w/a/s/d keys for moving",
                "          • mouse for turning/aiming and click for shooting",
                "      Else:",
                "          • decreases attack by 1/3",
                "          • attack needs 15 energy",
                "      Overall: easy to steer, does less damage and gets more damage",
                "",
                "Powerups:",
                "       Ram:",
                "           2x speed and collision attack (lasts 5 seconds)",
                "       Health-boost:",
                "           + 50 health (instantly)",
                "       Power-boost:",
                "           + 50 power (instantly)",
                "       Shield:",
                "           • indestructible against bullets (lasts 5 seconds)",
                "           • still damage from lava",
                "",
                "Modes:",
                "   Easy:",
                "       • 3 robots (1 player and 2 npcs)",
                "       • player has a speed advantage",
                "       • goal: be the last one alive",
                "   Medium:",
                "       • 4 robots (1 player and 3 npcs)",
                "       • player has a slight speed advantage",
                "       • goal: be the last one alive",
                "   Hard:",
                "       • 5 robots (1 player and 4 npcs)",
                "       • there are no speed advantages",
                "       • goal: be the last one alive",
                "   Survival1:",
                "       • in an increasingly fast time a new enemy appears",
                "       • hiding in bush does not work in survival mode",
                "       • one-shot-kill for enemies",
                "       • goal: survive as long as you can, make a new highscore",
                "   Survival2:",
                "       • always has 3 robots, everytime one dies, a faster one apppears",
                "       • hiding in bush does not work in survival mode",
                "       • one-shot-kill for enemies",
                "       • goal: survive as long as you can, make a new highscore",
                "",
                "Surfaces:",
                "   Grass:",
                "       no effect",
                "   Wall:",
                "       can not pass",
                "   Sand:",
                "       slower speed (while on sand)",
                "   Ice:",
                "       higher speed (while on ice)",
                "   Bush:",
                "       • invisible for all (while completly in bush)",
                "       • hiding in bush does not work in survival mode",
                "   Lava:",
                "       40 damage and respawn on safe surface",
            ],
            "lava_river": "Lava River",
            "four_elements": "Four Elements",
            "Random": "Random",
            "survival_mode_text": "Survival",
        }
    return texts
